### ISSUE TITLE
config file #enhancement

### ISSUE THREAD

**Issue by erikLundstedt** [ryze312/ff2mpv-rust#1]
would it be possible to implement a config file?
maybe using json as `serde_json` is [already a dependency](https://github.com/ryze312/ff2mpv-rust/blob/ab554ead23d73ed56764dee9d73e7ba57bf60c01/Cargo.toml#L6-L8):

a config file would be useful to, for example, start `mpv` with `-fs/--fullscreen` or possibly even replacing `mpv` completely, or prefixing/wrapping it with something like [gobble](https://github.com/EmperorPenguin18/gobble)

I have no experience/knowledge in rust, otherwise I would have made a PR as I dont think it would be hard(basically just parsing 1 or 2 json values and using those instead of the defaults if set)

**Comment by ryze312** [comment]
Sure, why not.
It would be easier and more useful to just have a value for a full command. 
Something like this
```json
{
    "mpv_command": "mpv --fs --vo=gpu --hwdec=vaapi"
}
```
I am not sure how to go about validating config for possible syntax and shell command errors. ff2mpv doesn't provide a way to do that. Although, it is possible to execute this script directly, not from the browser, so I can have an access to terminal output and report errors there.

**Comment by ryze312** [comment]
Available in [v1.1.0](https://github.com/ryze312/ff2mpv-rust/releases/tag/1.1.0)!
