### ISSUE TITLE
Use `--` to separate args and URLs

### ISSUE THREAD

**Issue by minijackson** [ryze312/ff2mpv-rust#10]
Hello and thanks for this tool!

I've noticed that the [original `ff2mpv` code](https://github.com/woodruffw/ff2mpv/blob/master/ff2mpv) was using `--` to separate args and urls, like this:

```bash
mpv --args -- $url
```

Which I think is good from a security perspective. Would you be open to adding it?

I've also seen that it always adds `--no-terminal` to the options (see https://github.com/woodruffw/ff2mpv/issues/1)

**Comment by ryze312** [comment]
Hey thanks for the suggestion! This is certainly a good idea, will implement shortly.
