### ISSUE TITLE
google-chrome not working

### ISSUE THREAD

**Issue by hdm9527** [ryze312/ff2mpv-rust#13]
Firefox can call mpv to play videos, but it cannot work using google-chrome, and there is no error message in the console.

>firefox

![image](https://github.com/ryze312/ff2mpv-rust/assets/39702328/c0d98c13-7c43-4e54-b11f-c32492544c80)

>chrome

![image](https://github.com/ryze312/ff2mpv-rust/assets/39702328/c11b3b10-231a-46cb-9089-0ea731b51088)

**Comment by ryze312** [comment]
Looks like Chromium browsers require the `chrome-extension://` to end with the leading slash, can you try adding it manually and testing again?

**Comment by hdm9527** [comment]
> Looks like Chromium browsers require the `chrome-extension://` to end with the leading slash, can you try adding it manually and testing again?

Adding '/' at the end still doesn't work.
![image](https://github.com/ryze312/ff2mpv-rust/assets/39702328/07ceead9-d3de-44d1-b839-d6380f8ee4da)

**Comment by ryze312** [comment]
Can you paste the contents of the manifest as is here in the code blocks?

**Comment by hdm9527** [comment]
> Can you paste the contents of the manifest as is here in the code blocks?

```
{
  "name": "ff2mpv",
  "description": "ff2mpv's external manifest",
  "path": "/usr/bin/ff2mpv-rust",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://ephjcajbkgplkjmelpglennepbpmdpjg/"
  ]
}
```

**Comment by ryze312** [comment]
Could you provide some more information? What distribution you are trying this on, what Chrome version and does this work with the original native client?

**Comment by hdm9527** [comment]
> Could you provide some more information? What distribution you are trying this on, what Chrome version and does this work with the original native client?

ArchLinux(Hyprland) 
Chrome: 123.0.6312.122-1
mpv: 1:0.37.0-3

I based on [FF2MPV Installation](https://github.com/woodruffw/ff2mp2mpv/wiki/installation-n-linux#chromium) and [Google's documentation](https://developer.chrome.com/docs/apps/nativeMessaging/#native-messaging-host-location) Configuration `ff2mpv.json`. No other native client can test.

**Comment by ryze312** [comment]
Looks like AUR package also writes manifest in `/etc/opt/chrome/native-messaging-hosts/ff2mpv.json`, maybe Chrome is picking up that instead of the one in your home directory? Try editing it.

**Comment by hdm9527** [comment]
> Looks like AUR package also writes manifest in `/etc/opt/chrome/native-messaging-hosts/ff2mpv.json`, maybe Chrome is picking up that instead of the one in your home directory? Try editing it.

Chrome made a copy of it myself, but I didn't create it.
![image](https://github.com/ryze312/ff2mpv-rust/assets/39702328/0b084575-abc2-422c-a5e8-698ebe216979)

**Comment by ryze312** [comment]
I would suggest trying with the original manifest and see if it works first, should be `ff2mpv-native-messaging-host-git` in AUR

**Comment by hdm9527** [comment]
> Looks like AUR package also writes manifest in `/etc/opt/chrome/native-messaging-hosts/ff2mpv.json`, maybe Chrome is picking up that instead of the one in your home directory? Try editing it.

Google Chrome's problem, chromium work, and lack of `/` at the end.
![image](https://github.com/ryze312/ff2mpv-rust/assets/39702328/7b963065-0fd4-462a-89e1-bbb798a53150)

**Comment by ryze312** [comment]
You mean the problem is with your Chrome installation? The only issue that I can reproduce is the lack of leading slash there. Does it work correctly on both browsers after adding it?

**Comment by hdm9527** [comment]
> You mean the problem is with your Chrome installation? The only issue that I can reproduce is the lack of leading slash there. Does it work correctly on both browsers after adding it?

Chrome still not working. Chromium works.

**Comment by hdm9527** [comment]
I tried changing the path to `/usr/bin/kitty` and successfully started kitty, which proves that Chrome’s NativeMessagingHosts configuration is correct.
![image](https://github.com/ryze312/ff2mpv-rust/assets/39702328/2e8e2ba1-b95f-4c91-8d0b-2329c332e2e7)

**Comment by azizsayfiddin** [comment]
Same

**Comment by azizsayfiddin** [comment]
I tried it on Brave and it works there. I also switched to it
