### ISSUE TITLE
help get rust working

### ISSUE THREAD

**Issue by geextahslex** [ryze312/ff2mpv-rust#3]
OS: Win 7 x64
mpv: latest v0.36.0

Hi,
I don't know how to get this working. I installed the addon for firefox. I downloaded the ff2mpv-rust.exe and I put the .json file inside appdata. But nothing happens. After running the .exe a command window appers but it doesn't react to any commands

Im a noob in regard of scripting and so on

Thank you for any help/suggestions

**Comment by ryze312** [comment]
Have you installed native messaging host, according to [the guide](https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows#firefox)? You can get the manifest (`ff2mpv-windows.json` in guide) by running `ff2mpv-rust.exe manifest`  from the command line.

**Comment by geextahslex** [comment]
I have not. I thought rust is a alternative solution? ^^ Im kinda overwhelmed, Im a casual windows user ^^'
I typed "ff2mpv-rust.exe manifest" but nothing happend.

**Comment by ryze312** [comment]
ff2mpv-rust is the alternative client for ff2mpv, that's correct.
Type in command line
```
cd  "path/to/where/you/installed/ff2mpv-rust"
ff2mpv-rust.exe manifest
```
Copy what the command prints and save it in some .txt file somewhere on your PC (you can save it in the same folder as ff2mpv-rust.exe, for convenience). Then follow [this section](https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows#firefox) of the guide using path to that .txt file.

**Comment by geextahslex** [comment]
Okay now I got this
![qqq](https://github.com/ryze312/ff2mpv-rust/assets/139760266/55007a25-33c1-4d34-8ffb-dc710e9d3c5a)

**Comment by ryze312** [comment]
Copy that and save inside some text file (for example in C:\ff2mpv-rust\messaging-host.json). Then follow [this section](https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows#firefox) of the guide using that path.

**Comment by geextahslex** [comment]
There is no "NativeMessagingHosts" in the Mozilla registry, should I create it?

**Comment by ryze312** [comment]
Yes

**Comment by geextahslex** [comment]
Why there is not a single screenshot how this suppose to look like, I dont get keys and values ^^ There are so many options.
![sdsdd](https://github.com/ryze312/ff2mpv-rust/assets/139760266/2a5a9532-8e35-4f24-8ae4-0880f03faa0a)

**Comment by ryze312** [comment]
I don't speak German, but I think you need to create a string key (that should be *Zeichenfolge* option)  named "ff2mpv". Set the value of that key to the path of your messaging-host.json

**Comment by geextahslex** [comment]
Okay I have no idea what to do now. What about this file? https://github.com/ryze312/ff2mpv-rust/blob/main/ff2mpv-rust.json

my json rust file from the cmd looks like this
{
  "name": "ff2mpv",
  "description": "ff2mpv's external manifest",
  "path": "F:\\Backup Windows\\Downloads\\rust\\ff2mpv-rust.exe",
  "type": "stdio",
  "allowed_origins": [
    "ff2mpv@yossarian.net"
  ]
}

PS. I have never seen such an atrocious "install guide" honestly one screenshot would solve the issue xD

**Comment by ryze312** [comment]
The file that you linked is the config file for ff2mpv-rust, it's not required to get it running if you don't want to change the player used or arguments for mpv, it is not required.

The file from cmd you got is the config file for native messaging host, that is required to setup Firefox for communicating between  **ff2mpv addon** and **ff2mpv-rust** (which starts up mpv).

Second file needs to be placed somewhere on your PC, the path to which is specified by the registry key you need to create 



> I don't speak German, but I think you need to create a string key (that should be _Zeichenfolge_ option) named "ff2mpv". Set the value of that key to the path of your messaging-host.json

**Comment by geextahslex** [comment]
I have but it is not working 
![registry](https://github.com/ryze312/ff2mpv-rust/assets/139760266/a1211927-aa08-46e1-a436-b083b038c7fd)

**Comment by ryze312** [comment]
Show the contents of ff2mpv-windows.json

**Comment by geextahslex** [comment]
{
  "name": "ff2mpv",
  "description": "ff2mpv's external manifest",
  "path": "F:\\Backup Windows\\Downloads\\rust\\ff2mpv-rust.exe",
  "type": "stdio",
  "allowed_origins": [
    "ff2mpv@yossarian.net"
  ]
}

I changed allowed_extensions with allowed_origins as it is in the guide?

**Comment by ryze312** [comment]
Is mpv.exe in PATH? If not, make a config file for ff2mpv-rust and specify absolute path to it there.

**Comment by geextahslex** [comment]
1. what do you mean with "in path"? mpv.exe is not in the same folder as rust.exe, they are in seperate folders
2. how do I make a config file and what I write there?

**Comment by ryze312** [comment]
Like such
```
{
    "player_command": "C:\\Program Files\\mpv\\mpv.exe",
    "player_args": ["--fullscreen"]
}
```

**Comment by geextahslex** [comment]
are you sure about this double \\ ?

So I made ff2mpv-rust.json in appdata/roaming with the text you posted (with my mpv.exe location), and its not working

**Comment by ryze312** [comment]
Not working how? Have you restarted Firefox after adding registry key?

**Comment by geextahslex** [comment]
Yes I have

**Comment by ryze312** [comment]
Go to any video on YouTube and click on ff2mpv extension icon, console window might flash

**Comment by geextahslex** [comment]
I have tried but the only thing that happens is that it pauses the youtube video

**Comment by ryze312** [comment]
Then there is a misconfiguration in your ff2mpv-windows.json config

**Comment by geextahslex** [comment]
yeah but which? I didnt change anything besides this allowed_origins thing

{
  "name": "ff2mpv",
  "description": "ff2mpv's external manifest",
  "path": "F:\\Backup Windows\\Downloads\\rust\\ff2mpv-rust.exe",
  "type": "stdio",
  "allowed_origins": [
    "ff2mpv@yossarian.net"
  ]
}

**Comment by ryze312** [comment]
Try double slashes in path

**Comment by ryze312** [comment]
If it still doesn't work, try creating a subkey (folder) in "NativeMessagingHosts" named "ff2mpv" and the default value for it should be your path to ff2mpv-windows.json

> I have but it is not working ![registry](https://user-images.githubusercontent.com/139760266/263838933-a1211927-aa08-46e1-a436-b083b038c7fd.png)

**Comment by geextahslex** [comment]
Thats exactly what I did now, and also not working ^^

**Comment by ryze312** [comment]
Show a screenshot

**Comment by geextahslex** [comment]
![4444](https://github.com/ryze312/ff2mpv-rust/assets/139760266/53fcdea2-007b-402a-a2e2-b1dc0afd4996)

**Comment by ryze312** [comment]
*(Standard)* specifies default value for a key, set it's value to that path

**Comment by geextahslex** [comment]
I tried, nothing ...^^'

**Comment by ryze312** [comment]
Then there is an issue either with an addon itself or your Firefox installation. Nothing I can do, I do not have Windows machine to test it out. You can try Python messaging host instead.

**Comment by geextahslex** [comment]
Okay, but thank you for your effort ^^

**Comment by geextahslex** [comment]
When I enter "ff2mpv-rust.exe validate"
then he says  JSON Error: trailing comma at line 4 column 1

**Comment by buzeak** [comment]
> Then there is a misconfiguration in your ff2mpv-windows.json config

Probably line 4, column 1 in this file. It is plain text, just open it and look at the start of line 4, or the end of line 3 might be missing a bracket or speech mark or something.

**Comment by geextahslex** [comment]
I just copied the manifest. I tried to find it, but its hard when you dont even understand the code ^^

{
  "name": "ff2mpv",
  "description": "ff2mpv's external manifest",
  "path": "C:\\Program Files\\rust\\ff2mpv-rust.exe",
  "type": "stdio",
  "allowed_origins": [
    "ff2mpv@yossarian.net"
  ]
}

**Comment by buzeak** [comment]
> yeah but which? I didnt change anything besides this allowed_origins thing
> 
> { "name": "ff2mpv", "description": "ff2mpv's external manifest", "path": "F:\Backup Windows\Downloads\rust\ff2mpv-rust.exe", "type": "stdio", "allowed_origins": [ "[ff2mpv@yossarian.net](mailto:ff2mpv@yossarian.net)" ] }

Maybe it's the apostrophe at this part?: "description": "ff2mpv's external manifest"

**Comment by ryze312** [comment]
This is still going? Amazing.



> I just copied the manifest. I tried to find it, but its hard when you dont even understand the code ^^
> 
> { "name": "ff2mpv", "description": "ff2mpv's external manifest", "path": "C:\Program Files\rust\ff2mpv-rust.exe", "type": "stdio", "allowed_origins": [ "[ff2mpv@yossarian.net](mailto:ff2mpv@yossarian.net)" ] }

Try double slashes as I suggested

**Comment by geextahslex** [comment]
I don't undestand, try double slashes or apostrophe xD

**Comment by ryze312** [comment]
Double slashes 
`"C:\\Program Files\\rust\\ff2mpv-rust.exe"`

**Comment by geextahslex** [comment]
sorry it changes it here.
![location](https://github.com/ryze312/ff2mpv-rust/assets/139760266/a3c54dbc-43ad-468e-940a-e2646249578d)

**Comment by ryze312** [comment]
Yes, looks good

**Comment by geextahslex** [comment]
not good enough ^^
![error](https://github.com/ryze312/ff2mpv-rust/assets/139760266/c8b15872-aac8-4cfc-9434-9abf496f2024)

**Comment by ryze312** [comment]
What's in the config file itself (`%APPDATA%\ff2mpv-rust.json`)?

**Comment by geextahslex** [comment]
![appdata config json](https://github.com/ryze312/ff2mpv-rust/assets/139760266/aa7ea9cd-5bfb-4bde-bf02-971aa337860b)

**Comment by ryze312** [comment]
There is a trailing comma as you can see, remove it

**Comment by geextahslex** [comment]
Okay config is now valid! thank you
but it still doesnt work ^^

**Comment by ryze312** [comment]
Restart Firefox and try again. Does the console window appear on launch?

**Comment by geextahslex** [comment]
Which launch? when I click the mpv buton?

**Comment by ryze312** [comment]
Yes

**Comment by geextahslex** [comment]
no there is no reaction T.T

**Comment by ryze312** [comment]
Try also adding that key to `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Mozilla\NativeMessagingHosts\` in the registry

**Comment by ryze312** [comment]
Maybe also `HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts\`

**Comment by geextahslex** [comment]
I made the first one, by the 2nd one there was already a "NativeMessagingHosts" folder. I also added there.
but no luck :P

**Comment by geextahslex** [comment]
So your rust is working on linux?

**Comment by ryze312** [comment]
it does work on Linux, I am not sure what's wrong with your installation. Configs are fine, it might just be that Firefox has broken messaging hosts on Windows. Try following "official" ff2mpv [guide](https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows) with Python script, that might work.

**Comment by geextahslex** [comment]
what can I type into the rust window, to try if it can trigger mpv?

**Comment by ryze312** [comment]
If that still doesn't work, it's not ff2mpv-rust problem, but rather ff2mpv itself. In such case, file an issue in their repo

**Comment by ryze312** [comment]
I am closing this off, as at this point it just a spam. GitHub issues are meant for code and behavior related problems, not for tech support.
