### ISSUE TITLE
ff2mpv-rust doesn't launch on Windows

### ISSUE THREAD

**Issue by TheLongLife** [ryze312/ff2mpv-rust#5]
Excuse my noob-iness. 
I'm trying to get this working on Windows.  

I have it working with the default client (python?) but it seems sluggish, how would I go about switching it with the rust one?  

I tried following the installation steps but it's not very clear to me what to do after I use the `ff2mpv-rust manifest` command.  
Should I swap the contents of **ff2mpv-windows.json**  with the output text I get after running the manifest command? (I've tried that but it doesn't work).
I also confirmed that the config is valid.

**Comment by ryze312** [comment]
Did you follow the steps outlined [here](https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows#manual-installation)? In your case, swapping out the contents of the JSON file should be enough.

What are the original contents of it and the output of `ff2mpv-rust manifest`?

**Comment by TheLongLife** [comment]
In the meantime, I also tried it on Vivaldi browser and it works just fine there, but not in the Firefox.   

>Did you follow the steps outlined [here](https://github.com/woodruffw/ff2mpv/wiki/Installation-on-Windows#manual-installation)?  

Yes, that is exactly the instruction that I followed.  

>What are the original contents of it and the output of ff2mpv-rust manifest?  

These were the original contents of **ff2mpv-windows.json**
```
{
    "name": "ff2mpv",
    "description": "ff2mpv's native manifest",
    "path": "ff2mpv.bat",
    "type": "stdio",
    "allowed_extensions": ["ff2mpv@yossarian.net"]
}
```
The output I get when I use the _manifest_ command is:

```
{
  "name": "ff2mpv",
  "description": "ff2mpv's external manifest",
  "path": "C:\\Miscellaneous tools\\ff2mpv-master\\ff2mpv-rust.exe",
  "type": "stdio",
  "allowed_extensions": [
    "ff2mpv@yossarian.net"
  ]
}

```

-----

This is what my JSON files look like:  

This is the one for the Vivaldi (this one works):  
**ff2mpv-windows-chrome.json**
```
{
    "name": "ff2mpv",
    "description": "ff2mpv's native manifest",
    "path": "C:\\Miscellaneous tools\\ff2mpv-master\\ff2mpv-rust.exe",
    "type": "stdio",
    "allowed_origins": ["chrome-extension://ephjcajbkgplkjmelpglennepbpmdpjg/"]
}
```

This one is for the Firefox (this one doesn't work):  
**ff2mpv-windows.json**
```
{
    "name": "ff2mpv",
    "description": "ff2mpv's native manifest",
    "path": "C:\\Miscellaneous tools\\ff2mpv-master\\ff2mpv-rust.exe",
    "type": "stdio",
    "allowed_extensions": ["ff2mpv@yossarian.net"]
}
```
_It works with the original client, `"path": "ff2mpv.bat",`_

**Comment by ryze312** [comment]
Interesting, where is `ff2mpv.bat` located at?

**Comment by TheLongLife** [comment]
> Interesting, where is `ff2mpv.bat` located at?

In the same folder where the JSON file is, so `C:\\Miscellaneous tools\\ff2mpv-master\\`
I also placed the *ff2mpv-rust.exe* in the same folder, and tried to use just the `"path": "ff2mpv-rust.exe",` , but that didn't work either.

**Comment by ryze312** [comment]
It might be  that Firefox doesn't allow executing EXE directly. 
What if you wrap it up in a batch script and call it there?
```bat
@echo off
call ff2mpv-rust.exe
```

**Comment by TheLongLife** [comment]
Actually I tried that as well, I forgot to mention. It didn't work either.  
I re-tried it right now and still nothing.

**Comment by ryze312** [comment]
Could you show how  you got the registry key set up?

**Comment by TheLongLife** [comment]
This one is for Vivaldi:
![image](https://github.com/ryze312/ff2mpv-rust/assets/10586628/4d4f05e8-d94c-4379-bd04-064f6744b202)

This one is for Firefox:
![image](https://github.com/ryze312/ff2mpv-rust/assets/10586628/c0f2560d-5510-403c-8f43-cc82e572a698)

**Comment by ryze312** [comment]
That looks right. This might just be a Windows-specific bug, as the script was only properly tested on Linux. 
I'll get access to Windows machine in a couple days and try to reproduce it.

**Comment by TheLongLife** [comment]
Alright, thank you for your time and effort.

**Comment by Samson7** [comment]
I confirm that i got the same bug on Windows 10 22h2 build 19045.3570 using custom-firefox browser Mercury. With original python script ff2mpv.py everything works as expected. Also i noticed that ff2mpv-rust doesn't recognize config file located in %APPDATA% as mentioned in the readme(if i execute ff2mpv-rust validate it says "Config doesn't exist"), so maybe that the reason why the native-host doesn't work?

**Comment by ryze312** [comment]
Can anyone verify if it works on the linked branch? I've published a pre-release with fix applied, if you don't want to compile it yourself.

**Comment by ryze312** [comment]
> I confirm that i got the same bug on Windows 10 22h2 build 19045.3570 using custom-firefox browser Mercury. With original python script ff2mpv.py everything works as expected. Also i noticed that ff2mpv-rust doesn't recognize config file located in %APPDATA% as mentioned in the readme(if i execute ff2mpv-rust validate it says "Config doesn't exist"), so maybe that the reason why the native-host doesn't work?

ff2mpv-rust will fallback to the default configuration if there is an error parsing config file. This is unrelated. Please check the path and name of the config file. If the problem persists, open up a new issue.

**Comment by TheLongLife** [comment]
> Can anyone verify if it works on the linked branch? I've published a pre-release with fix applied, if you don't want to compile it yourself.

I just tested it. It works now 👍

**Comment by ryze312** [comment]
Thanks for helping with the issue! I'll make a couple more changes and do a proper release soon.
